//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # translation for Japanese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Enable System Proxy=システム プロキシを有効にする
        ///Mode=モード
        ///PAC=PAC
        ///Global=全般
        ///Servers=サーバー
        ///Edit Servers...=サーバーの編集...
        ///Statistics Config...=統計情報の設定...
        ///Start on Boot=システムと同時に起動
        ///Forward Proxy...=フォワードプロキシの設定...
        ///Allow Clients from LAN=LAN からのアクセスを許可
        ///Local PAC=ローカル PAC
        ///Online PAC=オンライン PAC
        ///Edit Local PAC File...=ローカル PAC ファイルの編集...
        ///Update Local PAC from GFWList=GFWList からローカル PAC を更新
        ///Edit User Rule for GFWList...=ユーザールールの編集...
        ///Secure Local  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss_i {
            get {
                object obj = ResourceManager.GetObject("ss_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss_id {
            get {
                object obj = ResourceManager.GetObject("ss_id", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss_io {
            get {
                object obj = ResourceManager.GetObject("ss_io", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ss_o {
            get {
                object obj = ResourceManager.GetObject("ss_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # translation for Simplified Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Enable System Proxy=启用系统代理
        ///Mode=系统代理模式
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=服务器
        ///Edit Servers...=编辑服务器...
        ///Statistics Config...=统计配置...
        ///Start on Boot=开机启动
        ///Forward Proxy...=正向代理设置...
        ///Allow Clients from LAN=允许来自局域网的连接
        ///Local PAC=使用本地 PAC
        ///Online PAC=使用在线 PAC
        ///Edit Local PAC File...=编辑本地 PAC 文件...
        ///Update Local PAC from GFWList=从 GFWList 更新本地 PAC
        ///Edit User Rule for GFWList...=编辑 GFWList 的用户规则...
        ///Secure Local PAC=保护本地 PAC
        ///Cop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # translation for Traditional Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Enable System Proxy=啟用系統代理
        ///Mode=系統代理模式
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Servers=伺服器
        ///Edit Servers...=編輯伺服器...
        ///Statistics Config...=統計設定檔...
        ///Start on Boot=開機啟動
        ///Forward Proxy...=正向 Proxy 設定...
        ///Allow Clients from LAN=允許來自區域網路的連線
        ///Local PAC=使用本機 PAC
        ///Online PAC=使用線上 PAC
        ///Edit Local PAC File...=編輯本機 PAC 檔案...
        ///Update Local PAC from GFWList=從 GFWList 更新本機 PAC
        ///Edit User Rule for GFWList...=編輯 GFWList 的使用者規則...
        ///Secure Local PAC=安全本機 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_TW {
            get {
                return ResourceManager.GetString("zh_TW", resourceCulture);
            }
        }
    }
}
